Repository solvcon/modmesh, pull requests merged in 2022-06, with the labels that each got.

#82 Fix the bug that mesh is not drawn in the viewer
  .github/workflows/modmesh_install.yml
  .github/workflows/modmesh_pytest.yml
  cpp/modmesh/view/RStaticMesh.cpp
Labels: bug

#83 Add arrow heads to the lines of the axis markers
  cpp/modmesh/python/wrapper/view/wrap_view.cpp
  cpp/modmesh/view/RAxisMark.cpp
  cpp/modmesh/view/RAxisMark.hpp
  cpp/modmesh/view/RPythonText.cpp
Labels: enhancement

#86 Add text labels next to the axis marking lines
  cpp/modmesh/view/RAxisMark.cpp
  cpp/modmesh/view/RAxisMark.hpp
Labels: enhancement, viewer

#87 Take the pixmap from the 3D window
  cpp/binary/viewer/viewer.cpp
  cpp/modmesh/view/R3DWidget.hpp
Labels: enhancement, viewer

#90 Do not add "exit" menu item when it is macos
  cpp/modmesh/view/RApplication.cpp
Labels: enhancement

#94 Remove duplicated edges when drawing the wireframe of a mesh
  cpp/modmesh/mesh/StaticMesh.hpp
  cpp/modmesh/mesh/StaticMesh_interior.cpp
  cpp/modmesh/python/wrapper/modmesh/wrap_StaticMesh.cpp
  cpp/modmesh/view/RPythonText.cpp
  cpp/modmesh/view/RStaticMesh.cpp
  cpp/modmesh/view/common_detail.hpp
  tests/test_mesh.py
Labels: enhancement, viewer

#97 bump pybind11 from 2.6.1 to 2.9.2
  contrib/dependency/install.sh
Labels: test
