Repository solvcon/modmesh, pull requests merged in 2022-12, with the labels that each got.

#161 Integrate PySide to modmesh aid (viewer)
  .github/workflows/devbuild.yml
  CMakeLists.txt
  cpp/modmesh/CMakeLists.txt
  cpp/modmesh/toggle/pymod/wrap_Toggle.cpp
  cpp/modmesh/toggle/toggle.hpp
  cpp/modmesh/view/wrap_view.cpp
  modmesh/app/euler1d.py
  tests/test_toggle.py
Labels: enhancement

#163 Fix the Linux crash due to a bug using wrong type of argument to QApplication constructor
  cpp/modmesh/view/RApplication.cpp
  cpp/modmesh/view/RApplication.hpp
Labels: bug

#167 Fix qt geometry render issue by modified vertex size
  cpp/modmesh/view/RAxisMark.cpp
  cpp/modmesh/view/RStaticMesh.cpp
Labels: bug, viewer

#168 Output stack trace to std::cerr when Python exception is thrown from viewer
  cpp/modmesh/python/common.cpp
  cpp/modmesh/view/RAction.cpp
  cpp/modmesh/view/wrap_view.cpp
Labels: enhancement

#170 Revert fa21d6e18904df4c6c05f3d93c7f911e90f7b6f4
  cpp/modmesh/view/RAxisMark.cpp
  cpp/modmesh/view/RStaticMesh.cpp
Labels: bug, viewer

#177 build(Makefile): make python3-config protable
  Makefile
  cpp/binary/pymod_modmesh/CMakeLists.txt
Labels: enhancement

#174 Refactor to combine RApplication and RMainWindow
  cpp/modmesh/view/CMakeLists.txt
  cpp/modmesh/view/RApplication.hpp
  cpp/modmesh/view/RMainWindow.hpp
  cpp/modmesh/view/RManager.cpp
  cpp/modmesh/view/RManager.hpp
  cpp/modmesh/view/view.hpp
  cpp/modmesh/view/wrap_view.cpp
  modmesh/app/bad_euler1d.py
  modmesh/app/euler1d.py
  modmesh/app/linear_wave.py
  modmesh/app/sample_mesh.py
  modmesh/view.py
  tests/test_view.py
Labels: refactor, viewer

#180 Fix execvp permission denied error
  Makefile
Labels: bug

#183 Correct cmake support version of gtests
  gtests/CMakeLists.txt
Labels: bug, test
