Repository solvcon/modmesh, pull requests merged in 2022-05, with the labels that each got.

#63 fix: Clear scene before assign new mesh
  src/viewer/modmesh/viewer/PythonInterpreter.cpp
Labels: bug

#64 Correct the wrong deletion of the controller of scene
  src/viewer/modmesh/viewer/PythonInterpreter.cpp
Labels: bug

#65 Add a single tetrahedron mesh for testing 3D mesh code
  include/modmesh/mesh/interior.hpp
  include/modmesh/python/python.hpp
  src/viewer/modmesh/viewer/PythonInterpreter.cpp
  src/viewer/modmesh/viewer/R3DWidget.cpp
  src/viewer/modmesh/viewer/R3DWidget.hpp
  src/viewer/modmesh/viewer/RPythonText.cpp
  src/viewer/modmesh/viewer/RStaticMesh.hpp
  tests/test_mesh.py
Labels: enhancement

#71 Make StaticMesh a class instead of a template
  .clang-tidy
  CMakeLists.txt
  include/modmesh/base.hpp
  include/modmesh/mesh.hpp
  include/modmesh/mesh/StaticMesh.hpp
  include/modmesh/python/python.hpp
  modmesh/__init__.py
  src/modmesh/mesh/StaticMesh_boundary.cpp
  src/modmesh/mesh/StaticMesh_interior.cpp
  src/pymod/CMakeLists.txt
  src/viewer/modmesh/viewer/PythonInterpreter.cpp
  src/viewer/modmesh/viewer/RPythonText.cpp
  src/viewer/modmesh/viewer/RStaticMesh.hpp
  tests/test_mesh.py
Labels: enhancement

#79 Add a helper to convert QByteArray to SimpleArray
  .github/workflows/modmesh_viewer.yml
  cpp/modmesh/buffer/ConcreteBuffer.hpp
  cpp/modmesh/buffer/SimpleArray.hpp
  cpp/modmesh/view/RAxisMark.cpp
  cpp/modmesh/view/RStaticMesh.cpp
  cpp/modmesh/view/common_detail.hpp
Labels: enhancement

#80 Rename githuba action names
  .github/workflows/modmesh_format.yml
  .github/workflows/modmesh_install.yml
  .github/workflows/modmesh_pytest.yml
  .github/workflows/modmesh_viewer.yml
Labels: test
