Repository solvcon/modmesh, pull requests merged in 2022-11, with the labels that each got.

#143 Fix Python version to 3.10 on mac
  .github/workflows/devbuild.yml
  .github/workflows/lint.yml
  .github/workflows/nouse_install.yml
Labels: test

#140 WIP: fix Windows build warning
  .gitignore
  CMakeLists.txt
  cpp/modmesh/buffer/small_vector.hpp
  cpp/modmesh/mesh/StaticMesh.hpp
  cpp/modmesh/mesh/StaticMesh_boundary.cpp
  cpp/modmesh/mesh/StaticMesh_interior.cpp
  cpp/modmesh/onedim/Euler1DCore.cpp
  cpp/modmesh/onedim/Euler1DCore.hpp
  cpp/modmesh/python/common.hpp
  cpp/modmesh/python/wrapper/modmesh/TypeBroadcast.hpp
  cpp/modmesh/python/wrapper/modmesh/wrap_SimpleArray.cpp
  cpp/modmesh/python/wrapper/spacetime/wrap_spacetime.cpp
  cpp/modmesh/python/wrapper/spacetime/wrap_spacetime.hpp
  cpp/modmesh/spacetime/core.hpp
  cpp/modmesh/spacetime/kernel/BadEuler1DSolver.cpp
  cpp/modmesh/spacetime/kernel/BadEuler1DSolver.hpp
  cpp/modmesh/view/R3DWidget.cpp
  cpp/modmesh/view/RAxisMark.cpp
  cpp/modmesh/view/wrap_view.cpp
Labels: refactor

#146 Remove the Python text box at the right-hand side
  cpp/modmesh/view/CMakeLists.txt
  cpp/modmesh/view/RMainWindow.cpp
  cpp/modmesh/view/RMainWindow.hpp
  cpp/modmesh/view/RPythonConsoleDockWidget.cpp
  cpp/modmesh/view/RPythonConsoleDockWidget.hpp
  cpp/modmesh/view/RPythonText.cpp
  cpp/modmesh/view/RPythonText.hpp
  cpp/modmesh/view/view.hpp
  cpp/modmesh/view/wrap_view.cpp
  modmesh/app/bad_euler1d.py
  modmesh/app/euler1d.py
  modmesh/app/linear_wave.py
  modmesh/app/sample_mesh.py
  modmesh/view.py
Labels: enhancement

#147 Move code setting up main window to Python
  .github/workflows/devbuild.yml
  .github/workflows/lint.yml
  cpp/modmesh/view/CMakeLists.txt
  cpp/modmesh/view/RAction.cpp
  cpp/modmesh/view/RAction.hpp
  cpp/modmesh/view/RApplication.cpp
  cpp/modmesh/view/RApplication.hpp
  cpp/modmesh/view/RMainWindow.cpp
  cpp/modmesh/view/RMainWindow.hpp
  cpp/modmesh/view/wrap_view.cpp
  modmesh/app/bad_euler1d.py
  modmesh/app/euler1d.py
  modmesh/app/linear_wave.py
  modmesh/app/sample_mesh.py
  modmesh/system.py
  modmesh/view.py
Labels: refactor

#152 Improve the test case test_toggle:CommandLineInfoTC.test_populated
  tests/test_toggle.py
Labels: test

#153 Limit the number of anonymous environments in modmesh.apputil
  modmesh/apputil.py
  tests/test_apputil.py
Labels: enhancement

#148 Console stdout stderr
  cpp/binary/viewer/CMakeLists.txt
  cpp/modmesh/python/common.cpp
  cpp/modmesh/python/common.hpp
  cpp/modmesh/view/RPythonConsoleDockWidget.cpp
  cpp/modmesh/view/RPythonConsoleDockWidget.hpp
Labels: enhancement

#154 Add a whitespace after the ">>>" prompt in the console history
  cpp/modmesh/view/RPythonConsoleDockWidget.hpp
Labels: enhancement

#156 add error message if cannot find QT6
  cpp/modmesh/CMakeLists.txt
Labels: enhancement

#158 Add MDI support to viewer
  cpp/modmesh/view/R3DWidget.cpp
  cpp/modmesh/view/R3DWidget.hpp
  cpp/modmesh/view/RApplication.cpp
  cpp/modmesh/view/RApplication.hpp
  cpp/modmesh/view/RMainWindow.cpp
  cpp/modmesh/view/RMainWindow.hpp
  cpp/modmesh/view/RPythonConsoleDockWidget.cpp
  cpp/modmesh/view/RPythonConsoleDockWidget.hpp
  cpp/modmesh/view/wrap_view.cpp
  modmesh/app/sample_mesh.py
  modmesh/apputil.py
  modmesh/view.py
Labels: enhancement
