Repository solvcon/modmesh, pull requests merged in 2022-03, with the labels that each got.

#47 [Refactor] Create StaticMesh class template
  include/modmesh/mesh/StaticMesh_decl.hpp
Labels: refactor

#48 Add the stub of drawing a simple 2D mesh using Qt
  .clang-tidy
  .github/workflows/modmesh_install.yml
  .github/workflows/modmesh_pytest.yml
  CMakeLists.txt
  Makefile
  include/modmesh/mesh/StaticMesh_decl.hpp
  include/modmesh/profile.hpp
  src/pymod/CMakeLists.txt
  src/pymod/modmesh.cpp
  src/viewer/CMakeLists.txt
  src/viewer/main.cpp
  src/viewer/modmesh/viewer/viewer.hpp
Labels: enhancement

#49 Sync latest work from project/ustmesh
  .clang-tidy
  .github/workflows/modmesh_install.yml
  .github/workflows/modmesh_pytest.yml
  CMakeLists.txt
  Makefile
  include/modmesh/mesh/StaticMesh_decl.hpp
  include/modmesh/profile.hpp
  src/pymod/CMakeLists.txt
  src/pymod/modmesh.cpp
  src/viewer/CMakeLists.txt
  src/viewer/main.cpp
  src/viewer/modmesh/viewer/viewer.hpp
Labels: enhancement

#51 Add tests for SimpleArray
  include/modmesh/SimpleArray.hpp
  tests/test_buffer.py
Labels: test
