Repository solvcon/modmesh, pull requests merged in 2022-07, with the labels that each got.

#98 Refactor: Drop the unnecessary Python module preload
  cpp/modmesh/view/RApplication.cpp
  cpp/modmesh/view/RPythonText.cpp
Labels: refactor

#96 SimpleArray: support copy data from ndarray using ellipsis
  cpp/modmesh/python/wrapper/modmesh/wrap_SimpleArray.cpp
  tests/test_buffer.py
Labels: enhancement

#102 Fix viewer crash with linear_wave app loaded
  cpp/binary/viewer/viewer.cpp
  cpp/modmesh/python/common.cpp
  cpp/modmesh/python/common.hpp
  cpp/modmesh/view/RApplication.cpp
  cpp/modmesh/view/RApplication.hpp
  modmesh/app/__init__.py
  modmesh/app/linear_wave.py
Labels: bug

#108 Refactor spacetime and view
  .github/workflows/modmesh_lint.yml
  Makefile
  cpp/binary/pymod_modmesh/CMakeLists.txt
  cpp/binary/viewer/CMakeLists.txt
  cpp/binary/viewer/viewer.cpp
  cpp/modmesh/python/CMakeLists.txt
  cpp/modmesh/python/common.hpp
  cpp/modmesh/python/wrapper/spacetime/spacetime.cpp
  cpp/modmesh/python/wrapper/spacetime/wrap_spacetime.cpp
  cpp/modmesh/python/wrapper/spacetime/wrap_spacetime.hpp
  cpp/modmesh/python/wrapper/view/CMakeLists.txt
  cpp/modmesh/python/wrapper/view/view.cpp
  cpp/modmesh/spacetime/CMakeLists.txt
  cpp/modmesh/spacetime/Celm.hpp
  cpp/modmesh/spacetime/Celm_decl.hpp
  cpp/modmesh/spacetime/ElementBase.hpp
  cpp/modmesh/spacetime/ElementBase_decl.hpp
  cpp/modmesh/spacetime/Field.hpp
  cpp/modmesh/spacetime/Field_decl.hpp
  cpp/modmesh/spacetime/Grid_decl.hpp
  cpp/modmesh/spacetime/Selm.hpp
  cpp/modmesh/spacetime/Selm_decl.hpp
  cpp/modmesh/spacetime/Solver.hpp
  cpp/modmesh/spacetime/SolverBase.hpp
  cpp/modmesh/spacetime/SolverBase_decl.hpp
  cpp/modmesh/spacetime/base_spacetime.hpp
  cpp/modmesh/spacetime/core.cpp
  cpp/modmesh/spacetime/core.hpp
  cpp/modmesh/spacetime/io.cpp
  cpp/modmesh/spacetime/io.hpp
  cpp/modmesh/spacetime/kernel/inviscid_burgers.hpp
  cpp/modmesh/spacetime/kernel/linear_scalar.hpp
  cpp/modmesh/spacetime/spacetime.hpp
  cpp/modmesh/view/CMakeLists.txt
  cpp/modmesh/view/common_detail.hpp
  cpp/modmesh/view/view.hpp
  cpp/modmesh/view/wrap_view.cpp
  cpp/modmesh/view/wrap_view.hpp
Labels: refactor, viewer, spacetime

#109 Create a new option to animate the linear solver plot
  modmesh/app/linear_wave.py
Labels: enhancement

#107 SimpleArray: setitem parser & broadcast array by slices
  cpp/modmesh/python/wrapper/modmesh/wrap_SimpleArray.cpp
  tests/test_buffer.py
Labels: enhancement
