Repository solvcon/modmesh, pull requests merged in 2022-10, with the labels that each got.

#124 Fix errors reported by clang-tidy v15 and maintain the gha workflows
  .github/workflows/devbuild.yml
  .github/workflows/lint.yml
  .github/workflows/modmesh_format.yml
  .github/workflows/modmesh_install.yml
  .github/workflows/modmesh_lint.yml
  .github/workflows/modmesh_pytest.yml
  .github/workflows/modmesh_viewer.yml
  .github/workflows/nouse_install.yml
  CMakeLists.txt
  contrib/dependency/install.sh
  contrib/dependency/showdep.sh
  cpp/modmesh/buffer/small_vector.hpp
  cpp/modmesh/mesh/StaticMesh_boundary.cpp
  cpp/modmesh/mesh/StaticMesh_interior.cpp
  cpp/modmesh/profile.hpp
  cpp/modmesh/python/common.hpp
  cpp/modmesh/python/wrapper/modmesh/wrap_SimpleArray.cpp
  cpp/modmesh/python/wrapper/spacetime/wrap_spacetime.hpp
  cpp/modmesh/spacetime/core.hpp
Labels: test

#126 (Re-)fix clang-tidy errors that show up with v15
  .clang-tidy
  cpp/modmesh/onedim/Euler1DSolver.cpp
  cpp/modmesh/python/common.hpp
  cpp/modmesh/spacetime/kernel/BadEuler1DSolver.cpp
  cpp/modmesh/spacetime/kernel/BadEuler1DSolver.hpp
Labels: bug

#123 refactor wrapper of SimpleArray
  cpp/modmesh/python/wrapper/modmesh/CMakeLists.txt
  cpp/modmesh/python/wrapper/modmesh/TypeBroadcast.hpp
  cpp/modmesh/python/wrapper/modmesh/wrap_SimpleArray.cpp
Labels: refactor

#128 Create Python middle layer for the 1D Euler solver
  cpp/modmesh/onedim/CMakeLists.txt
  cpp/modmesh/onedim/Euler1DCore.cpp
  cpp/modmesh/onedim/Euler1DCore.hpp
  cpp/modmesh/onedim/onedim.hpp
  cpp/modmesh/python/wrapper/onedim/wrap_onedim.cpp
  modmesh/app/euler1d.py
  modmesh/onedim.py
  modmesh/onedim/__init__.py
  modmesh/onedim/_euler1d.py
  setup.py
  tests/test_onedim_euler.py
Labels: enhancement

#129 Update nouse_install.yml to disable automatic rootdir determination
  .github/workflows/nouse_install.yml
Labels: test

#134 Add code for the analytical solution of the shock tube problem
  cpp/modmesh/python/wrapper/onedim/wrap_onedim.cpp
  modmesh/app/euler1d.py
  modmesh/onedim/__init__.py
  modmesh/onedim/_euler1d.py
  modmesh/onedim/euler1d.py
  tests/test_onedim_euler.py
Labels: enhancement

#136 Make the viewer binary a multi-purpose binary
  .github/workflows/devbuild.yml
  Makefile
  cpp/binary/viewer/CMakeLists.txt
  cpp/binary/viewer/viewer.cpp
  cpp/modmesh/python/common.cpp
  cpp/modmesh/python/common.hpp
  cpp/modmesh/view/RApplication.cpp
  cpp/modmesh/view/RApplication.hpp
  cpp/modmesh/view/wrap_view.cpp
  modmesh/__init__.py
  modmesh/app/bad_euler1d.py
  modmesh/app/euler1d.py
  modmesh/app/linear_wave.py
  modmesh/app/sample_mesh.py
  modmesh/system.py
Labels: enhancement

#138 Add a new --mode=python by using the standard Python interpreter entry point
  cpp/binary/viewer/viewer.cpp
  cpp/modmesh/buffer/small_vector.hpp
  cpp/modmesh/python/common.cpp
  cpp/modmesh/python/common.hpp
  cpp/modmesh/python/wrapper/modmesh/wrap_Toggle.cpp
  cpp/modmesh/toggle/toggle.cpp
  cpp/modmesh/toggle/toggle.hpp
  modmesh/__init__.py
  modmesh/core.py
  modmesh/system.py
  tests/test_profile.py
  tests/test_toggle.py
Labels: enhancement

#139 Enable clang-tidy on the viewer
  .github/workflows/lint.yml
  CMakeLists.txt
  Makefile
  cpp/binary/viewer/CMakeLists.txt
  cpp/modmesh/python/common.cpp
  cpp/modmesh/view/.clang-tidy
  cpp/modmesh/view/R3DWidget.hpp
  cpp/modmesh/view/RApplication.cpp
  modmesh/__init__.py
Labels: test

#141 Move (macos) metal device initialization code
  cpp/binary/viewer/viewer.cpp
  cpp/modmesh/toggle/toggle.cpp
  cpp/modmesh/toggle/toggle.hpp
Labels: refactor
