Repository solvcon/modmesh, pull requests merged in 2023-05, with the labels that each got.

#216 add Qt main window module level handler in view module
  modmesh/view.py
Labels: bug, viewer

#221 Remove modmesh use pyside
  .github/workflows/devbuild.yml
  .github/workflows/lint.yml
  CMakeLists.txt
  cpp/modmesh/CMakeLists.txt
  cpp/modmesh/toggle/toggle.cpp
  cpp/modmesh/view/wrap_view.cpp
Labels: bug, build

#225 Use toggle for python_redirect
  cpp/modmesh/python/common.cpp
  cpp/modmesh/python/common.hpp
  cpp/modmesh/toggle/pymod/wrap_Toggle.cpp
  cpp/modmesh/toggle/toggle.hpp
  cpp/modmesh/view/RPythonConsoleDockWidget.cpp
  cpp/modmesh/view/RPythonConsoleDockWidget.hpp
Labels: enhancement

#226 Label the executed commands with serial number
  cpp/modmesh/view/RPythonConsoleDockWidget.cpp
  cpp/modmesh/view/RPythonConsoleDockWidget.hpp
Labels: enhancement, viewer

#227 Fix windows ci
  .github/workflows/devbuild.yml
  CMakeLists.txt
Labels: bug, build

#228 Remove ubuntu-20.04 and macos-11 from nouse_install.yml
  .github/workflows/nouse_install.yml
Labels: build
