Repository solvcon/modmesh, pull requests merged in 2024-04, with the labels that each got.

#309 Fix Github Actions mac failure
  .github/workflows/devbuild.yml
  .github/workflows/lint.yml
  .github/workflows/nouse_install.yml
  contrib/dependency/install.sh
Labels: test

#303 arrayplex setitem & refactoring
  cpp/modmesh/buffer/CMakeLists.txt
  cpp/modmesh/buffer/SimpleArray.hpp
  cpp/modmesh/buffer/pymod/TypeBroadcast.hpp
  cpp/modmesh/buffer/pymod/array_common.hpp
  cpp/modmesh/buffer/pymod/wrap_SimpleArray.cpp
  cpp/modmesh/buffer/pymod/wrap_SimpleArrayPlex.cpp
  cpp/modmesh/python/common.hpp
  tests/test_buffer.py
Labels: refactor

#311 use modern C++ std::add_pointer_t in `cpp/modmesh/python/common.hpp`
  cpp/modmesh/python/common.hpp
Labels: refactor

#310 remove DEBUG_BUILD_OPTIMIZATION_ONE
  .github/workflows/devbuild.yml
  .github/workflows/lint.yml
  CMakeLists.txt
  cpp/modmesh/buffer/pymod/array_common.hpp
  cpp/modmesh/buffer/pymod/wrap_SimpleArray.cpp
Labels: test, array

#292 [CI] add qt action to all platform
  .github/workflows/devbuild.yml
  .github/workflows/lint.yml
Labels: test

#316 `BufferExpander::m_end` is used before initialization
  cpp/modmesh/buffer/BufferExpander.hpp
  cpp/modmesh/buffer/pymod/wrap_ConcreteBuffer.cpp
  tests/test_buffer.py
Labels: bug, array

#317 support array broadcast with list/tuple
  cpp/modmesh/buffer/pymod/array_common.hpp
  tests/test_buffer.py
Labels: array

#319 Add a basic drawer for the NACA 4-digit airfoil
  cpp/modmesh/universe/World.hpp
  cpp/modmesh/universe/bezier.hpp
  cpp/modmesh/universe/pymod/wrap_World.cpp
  cpp/modmesh/view/RManager.cpp
  cpp/modmesh/view/RWorld.cpp
  modmesh/app/naca.py
  modmesh/core.py
  tests/test_universe.py
Labels: viewer, mesh
