Repository solvcon/modmesh, pull requests merged in 2024-07, with the labels that each got.

#376 Add the statistic function in the profiler
  cpp/modmesh/toggle/CMakeLists.txt
  cpp/modmesh/toggle/RadixTree.cpp
  cpp/modmesh/toggle/RadixTree.hpp
  cpp/modmesh/toggle/profile.cpp
  cpp/modmesh/toggle/profile.hpp
  cpp/modmesh/toggle/pymod/wrap_profile.cpp
  tests/test_callprofiler.py
Labels: enhancement, performance

#386 add clone for SimpleArray
  cpp/modmesh/buffer/pymod/wrap_SimpleArray.cpp
  cpp/modmesh/buffer/pymod/wrap_SimpleArrayPlex.cpp
  tests/test_buffer.py
Labels: enhancement, array

#388 support std::unordered_map for JSON Serializable
  cpp/modmesh/serialization/SerializableItem.hpp
  gtests/test_nopython_serializable.cpp
Labels: enhancement, performance

#381 Add download description for Windows nightly build
  README.md
Labels: documentation, build

#392 Add README content: make it explicit modmesh is modules using meshes
  README.md
  README.rst
Labels: documentation

#393 Add the directive for the direct download link
  README.rst
Labels: documentation

#390 use custom meta path finder to import 3rd library
  modmesh/pylibmgr.py
  modmesh/view.py
  tests/test_pylibmgr.py
Labels: enhancement, viewer

#394 Add STYLE.rst for coding style guide
  STYLE.rst
Labels: documentation

#385 Camera: use WASD+EQ and arrows+Page Up/Down for movement
  cpp/modmesh/view/CMakeLists.txt
  cpp/modmesh/view/R3DWidget.cpp
  cpp/modmesh/view/R3DWidget.hpp
  cpp/modmesh/view/RCameraController.cpp
  cpp/modmesh/view/RCameraController.hpp
  cpp/modmesh/view/view.hpp
  cpp/modmesh/view/wrap_view.cpp
  modmesh/view.py
  tests/test_view.py
Labels: viewer

#398 Fix the missing application icon under macos
  cpp/binary/viewer/CMakeLists.txt
  resources/viewer/solvcon.icns
Labels: bug, viewer
