Repository solvcon/modmesh, pull requests merged in 2024-08, with the labels that each got.

#402 Use the repository variable MMGH_NIGHTLY to control scheduled Github Actions run
  .github/workflows/devbuild.yml
  .github/workflows/lint.yml
  .github/workflows/nouse_install.yml
Labels: test

#384 Use cubic Bézier curve to sample NACA 4-digit airfoil
  modmesh/gui/naca.py
Labels: viewer, mesh

#403 Add placeholder for the 2/3D Euler CESE solver
  cpp/modmesh/CMakeLists.txt
  cpp/modmesh/multidim/CMakeLists.txt
  cpp/modmesh/multidim/euler.hpp
  cpp/modmesh/multidim/multidim.hpp
  cpp/modmesh/multidim/pymod/multidim_pymod.cpp
  cpp/modmesh/multidim/pymod/multidim_pymod.hpp
  cpp/modmesh/multidim/pymod/wrap_multidim.cpp
  cpp/modmesh/python/module.cpp
  modmesh/core.py
  tests/test_euler.py
Labels: multidim

#407 Temporarily turn off the linter run on macos-14
  .github/workflows/lint.yml
Labels: test

#397 Rebuild the serializer of the profiler with general serializer
  cpp/modmesh/toggle/CMakeLists.txt
  cpp/modmesh/toggle/RadixTree.cpp
  cpp/modmesh/toggle/RadixTree.hpp
  cpp/modmesh/toggle/SerializableProfiler.hpp
  cpp/modmesh/toggle/pymod/wrap_profile.cpp
  gtests/CMakeLists.txt
  gtests/test_nopython_callprofilerserializer.cpp
  tests/test_callprofiler.py
Labels: performance

#409 Add the syntax highlighting.
  STYLE.rst
Labels: documentation

#413 Fix the typo in README.rst
  README.rst
Labels: documentation, defect

#408 Camera: Add movement items to view menu
  cpp/modmesh/view/R3DWidget.cpp
  cpp/modmesh/view/R3DWidget.hpp
  cpp/modmesh/view/RCameraController.cpp
  cpp/modmesh/view/RCameraController.hpp
  cpp/modmesh/view/RManager.cpp
  cpp/modmesh/view/RManager.hpp
  cpp/modmesh/view/wrap_view.cpp
Labels: enhancement, viewer

#417 Edit style: always add curly braces
  STYLE.rst
Labels: documentation

#414 GUI configuration supporting string based access
  modmesh/app/euler1d.py
Labels: viewer, onedim

#418 Camera Controller: expose complete API to python
  cpp/modmesh/view/R3DWidget.cpp
  cpp/modmesh/view/R3DWidget.hpp
  cpp/modmesh/view/RCameraController.cpp
  cpp/modmesh/view/RCameraController.hpp
  cpp/modmesh/view/RManager.cpp
  cpp/modmesh/view/wrap_view.cpp
  tests/test_view.py
Labels: enhancement, viewer
