Repository solvcon/modmesh, pull requests merged in 2024-06, with the labels that each got.

#323 Prototype JSON serializer for `CallProfiler`
  cpp/modmesh/toggle/RadixTree.cpp
  cpp/modmesh/toggle/RadixTree.hpp
  gtests/CMakeLists.txt
  gtests/test_nopython_callprofiler.cpp
  gtests/test_nopython_callprofilerserializer.cpp
Labels: performance

#349 add missing function in BufferExpander
  cpp/modmesh/buffer/BufferExpander.hpp
Labels: array

#352 improve the comment in gtests
  gtests/CMakeLists.txt
Labels: test, refactor

#356 Reorder menu bar
  cpp/modmesh/view/RManager.cpp
  cpp/modmesh/view/RManager.hpp
Labels: viewer

#358 add gtest for ConcreteBuffer, SimpleArray and BufferExpander
  gtests/test_nopython_buffer.cpp
Labels: test, array

#359 Fix euler1d not responding on Windows
  modmesh/app/euler1d.py
Labels: bug, viewer

#360 Add items under "mesh" menu
  cpp/modmesh/view/RAction.cpp
  cpp/modmesh/view/RAction.hpp
  cpp/modmesh/view/RManager.cpp
  modmesh/gui/__init__.py
  modmesh/gui/naca.py
  modmesh/gui/sample_mesh.py
Labels: enhancement, viewer

#363 Implement `BufferBase` for the common part between `ConcreteBuffer` and `BufferExpander`
  cpp/modmesh/buffer/BufferBase.hpp
  cpp/modmesh/buffer/BufferExpander.hpp
  cpp/modmesh/buffer/CMakeLists.txt
  cpp/modmesh/buffer/ConcreteBuffer.hpp
Labels: refactor, array

#368 [hotfix] Improve CI Qt download stability
  .github/workflows/devbuild.yml
  .github/workflows/lint.yml
  thirdparty/aqt_settings.ini
Labels: bug, build

#367 fix the incorrect constructor initialization
  cpp/modmesh/buffer/BufferBase.hpp
  cpp/modmesh/buffer/BufferExpander.hpp
  cpp/modmesh/buffer/ConcreteBuffer.hpp
Labels: bug, array

#370 Viewer Windows Nightly Build
  .github/workflows/devbuild.yml
Labels: enhancement, viewer, build

#315 Add Python wrap to `CallProfiler`
  .github/workflows/devbuild.yml
  .github/workflows/lint.yml
  .github/workflows/nouse_install.yml
  cpp/modmesh/toggle/RadixTree.hpp
  cpp/modmesh/toggle/pymod/wrap_profile.cpp
  cpp/modmesh/toggle/toggle.hpp
  modmesh/core.py
  tests/data/profiler_python_schema.json
  tests/test_callprofiler.py
Labels: enhancement, performance

#372 add json serialization
  cpp/modmesh/CMakeLists.txt
  cpp/modmesh/base.hpp
  cpp/modmesh/serialization/CMakeLists.txt
  cpp/modmesh/serialization/SerializableItem.cpp
  cpp/modmesh/serialization/SerializableItem.hpp
  gtests/CMakeLists.txt
  gtests/test_nopython_serializable.cpp
Labels: enhancement, performance

#375 Add Reset within View menu
  cpp/modmesh/view/R3DWidget.cpp
  cpp/modmesh/view/R3DWidget.hpp
  cpp/modmesh/view/RManager.cpp
  cpp/modmesh/view/wrap_view.cpp
Labels: enhancement, viewer

#364 use systematic way to locate third-party lib
  modmesh/core.py
  modmesh/pylibmgr.py
  modmesh/view.py
  tests/test_pylibmgr.py
Labels: enhancement, viewer, build

#377 SerializableItem: implement JSON from string
  cpp/modmesh/base.hpp
  cpp/modmesh/serialization/SerializableItem.cpp
  cpp/modmesh/serialization/SerializableItem.hpp
  gtests/test_nopython_serializable.cpp
Labels: enhancement, performance
