Repository solvcon/modmesh, pull requests merged in 2025-07, with the labels that each got.

#551 Fix: Duplicate dft operation the result should be the same
  cpp/modmesh/transform/fourier.hpp
  tests/test_transform.py
Labels: array

#550 Add more options to edit the plot configuration
  modmesh/pilot/_base_app.py
Labels: pilot, onedim

#553 Fancy Profiling Table
  modmesh/profiling/__init__.py
  modmesh/profiling/__main__.py
  modmesh/profiling/_result.py
  setup.py
  tests/test_profiling_result.py
Labels: performance
