Repository solvcon/modmesh, pull requests merged in 2025-02, with the labels that each got.

#466 Fix the issue that freezes `SimpleCollector::push_back` from 2 -> 3
  cpp/modmesh/buffer/SimpleCollector.hpp
  tests/test_buffer.py
  tests/test_universe.py
Labels: bug, array

#467 Draw vertices as points using Qt3D
  cpp/modmesh/pilot/R3DWidget.cpp
  cpp/modmesh/pilot/RWorld.cpp
  cpp/modmesh/pilot/RWorld.hpp
  modmesh/pilot/_gui.py
  modmesh/pilot/_mesh.py
Labels: pilot

#456 Implement `sort`, `argsort` and `take_along_axis` for one dimensional `SimpleArray`
  cpp/modmesh/buffer/SimpleArray.hpp
  cpp/modmesh/buffer/pymod/wrap_SimpleArray.cpp
  tests/test_buffer.py
Labels: array

#470 Create `PointPad` expandable columnar container
  cpp/modmesh/buffer/SimpleCollector.hpp
  cpp/modmesh/universe/bezier.hpp
  cpp/modmesh/universe/pymod/wrap_World.cpp
  modmesh/core.py
  tests/test_universe.py
Labels: geometry

#471 Use `modmesh::PointPad` for calculating airfoil
  cpp/modmesh/universe/bezier.hpp
  cpp/modmesh/universe/pymod/wrap_World.cpp
  modmesh/pilot/airfoil/_naca.py
  tests/test_pilot_airfoil.py
  tests/test_universe.py
Labels: geometry

#472 Refactor: rename `Vector3d` to `Point3d` and `Edge3d` to `Segment3d`
  cpp/modmesh/pilot/RWorld.cpp
  cpp/modmesh/universe/World.hpp
  cpp/modmesh/universe/bezier.hpp
  cpp/modmesh/universe/pymod/wrap_World.cpp
  modmesh/core.py
  modmesh/pilot/_mesh.py
  modmesh/pilot/airfoil/_naca.py
  tests/test_universe.py
Labels: geometry

#473 Refactor: fix `Point3d` operator overload Python wrapper
  cpp/modmesh/universe/pymod/wrap_World.cpp
Labels: refactor, geometry

#468 add complex array support
  contrib/standalone_buffer/Makefile
  cpp/modmesh/buffer/SimpleArray.cpp
  cpp/modmesh/buffer/SimpleArray.hpp
  cpp/modmesh/buffer/pymod/SimpleArrayCaster.hpp
  cpp/modmesh/buffer/pymod/TypeBroadcast.hpp
  cpp/modmesh/buffer/pymod/array_common.hpp
  cpp/modmesh/buffer/pymod/wrap_SimpleArray.cpp
  cpp/modmesh/buffer/pymod/wrap_SimpleArrayPlex.cpp
  cpp/modmesh/math/Complex.hpp
  cpp/modmesh/math/pymod/wrap_Complex.cpp
  cpp/modmesh/python/common.hpp
  cpp/modmesh/transform/fourier.hpp
  gtests/test_nopython_transform.cpp
  modmesh/core.py
  tests/test_math.py
Labels: array
